spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # drop table when spring started
#      ddl-auto: none  # table drop x
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # collection 안에 있는 collection 을 가져오기 위한 in query의 개수

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
